version: '3.8'

services:
  web:
    image: ${IMAGE_NAME}
    ports:
      - "8280:80"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "app=vite-portfolio"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: overlay
